# Generated by Django 3.1.6 on 2021-04-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210413_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='jerseyNumber',
            field=models.IntegerField(default=0),
        ),
    ]
