# Generated by Django 3.1.6 on 2021-04-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210413_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
