# Generated by Django 3.1.6 on 2021-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_nbaplayer_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaplayer',
            name='totalRebounds',
            field=models.IntegerField(default=0),
        ),
    ]
