# Generated by Django 3.1.6 on 2021-05-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_nbaplayer_totalrebounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalPoints',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalRebounds',
            field=models.FloatField(default=0.0),
        ),
    ]
