# Generated by Django 3.1.6 on 2021-05-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210526_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalPoints',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalRebounds',
            field=models.FloatField(null=True),
        ),
    ]
