# Generated by Django 3.1.6 on 2021-05-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210526_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalPoints',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='totalRebounds',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
