# Generated by Django 3.1.6 on 2021-05-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210526_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaplayer',
            name='firstName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='jerseyNumber',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='lastName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nbaplayer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.nbateam'),
        ),
    ]
