# Generated by Django 3.1.6 on 2021-05-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210526_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbaplayer',
            name='jerseyNumber',
        ),
    ]
