# Generated by Django 3.1.6 on 2021-05-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_nbaplayer_jerseynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='city',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nbateam',
            name='mascot',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nbateam',
            name='teamName',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
