# Generated by Django 3.1.6 on 2021-05-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210527_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAPlayer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsPerGame', models.FloatField(default=0.0, null=True)),
                ('player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.nbaplayer')),
            ],
        ),
    ]
