# Generated by Django 3.1.6 on 2021-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_nbaplayer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbaplayer2',
            name='pointsPerGame',
        ),
        migrations.AddField(
            model_name='nbaplayer2',
            name='gamesPlayed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer2',
            name='threePointPer',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='nbaplayer2',
            name='twoPointPer',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
